// Generated by Apple Swift version 2.0 (swiftlang-700.0.57.3 clang-700.0.72)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol SKCacheManagerDelegate;
@class UIWebView;

SWIFT_CLASS("_TtC9SlidesKit14SKCacheManager")
@interface SKCacheManager : NSObject <UIWebViewDelegate>
@property (nonatomic, readonly, copy) NSString * __nonnull dirPath;
@property (nonatomic) id <SKCacheManagerDelegate> __nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)webViewDidFinishLoad:(UIWebView * __nonnull)webView;
- (void)retrieve:(NSString * __nonnull)dirPath;
- (void)rebuildCache:(NSString * __nonnull)dirPath;
@end

@class SKInfo;

SWIFT_PROTOCOL("_TtP9SlidesKit22SKCacheManagerDelegate_")
@protocol SKCacheManagerDelegate
@optional
- (void)retrievalDidFinish:(SKCacheManager * __nonnull)cacheManager cache:(NSArray<SKInfo *> * __nonnull)cache;
- (void)rebuildingDidFinish:(SKCacheManager * __nonnull)cacheManager cache:(NSArray<SKInfo *> * __nonnull)cache;
- (void)retrievalProgressReported:(SKCacheManager * __nonnull)cacheManager percent:(float)percent;
- (void)rebuildingProgressReported:(SKCacheManager * __nonnull)cacheManager percent:(float)percent;
@end

@class NSURL;
@class UIImage;

SWIFT_CLASS("_TtC9SlidesKit6SKInfo")
@interface SKInfo : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull dirPath;
@property (nonatomic, readonly, copy) NSString * __nonnull fileName;
@property (nonatomic, readonly, copy) NSString * __nonnull filePath;
@property (nonatomic, readonly, copy) NSString * __nonnull name;
@property (nonatomic, readonly, copy) NSString * __nonnull ext;
@property (nonatomic, readonly, copy) NSString * __nonnull type;
@property (nonatomic, readonly, copy) NSString * __nonnull creationData;
@property (nonatomic, readonly, copy) NSString * __nonnull modificationData;
@property (nonatomic, readonly) NSURL * __nonnull url;
@property (nonatomic, readonly) NSInteger numberOfPages;
@property (nonatomic, readonly) UIImage * __nonnull thumbnail;
@end

@class NSCoder;

SWIFT_CLASS("_TtC9SlidesKit12SKSlidesView")
@interface SKSlidesView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)load:(NSString * __nonnull)filePath;
- (void)gotoPage:(NSInteger)pageNumber;
- (void)nextPage;
- (void)prevPage;
- (void)firstPage;
- (void)finalPage;
@end


@interface UIImage (SWIFT_EXTENSION(SlidesKit))
@end


@interface UIView (SWIFT_EXTENSION(SlidesKit))
@end


@interface UIWebView (SWIFT_EXTENSION(SlidesKit))
@end

#pragma clang diagnostic pop
